"""The AI-provenance notice stamped onto every generated document.

Generated files leave Onyx and get mailed around. Once detached from the chat
that produced them they carry the authority of a finished company document, so
the warning has to travel *inside* the file rather than sit beside it in the UI.

There is deliberately no way to switch this off. A disclaimer users can disable
would be disabled on exactly the documents that travel furthest.
"""

# Kept short enough to sit in a page footer without wrapping to three lines.
DISCLAIMER_TEXT = (
    "AI-generated by NaArNi Gyan. May contain errors — verify before relying on it."
)

# Longer form for surfaces with room (cover pages, a dedicated CSV/XLSX row).
DISCLAIMER_TEXT_LONG = (
    "This document was generated by AI from a chat conversation. "
    "It may contain inaccuracies or omissions. "
    "Verify all figures and claims against source systems before relying on it."
)
